eshop/urls.py
from django.contrib import admin
from django.urls import path , include
from django.http import HttpResponse
from django.contrib.sessions.models import Session


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('home.urls')),
    path('user/' , include('users.urls' , namespace='client_app'))
]

home/urls.py
from django.urls import path
from .views import (home as H ,
    calculator , result ,
    exchange , about , book_detail , author_detail )

urlpatterns = [
    path('' , H),
    path('about/' , about),
    path('calculator/' , calculator),
    path('result/' , result),
    path('exchange/' , exchange),
    path('book-detail/<int:book_id>/' , book_detail),
    path('author-detail/<int:author_id>/' , author_detail),
]

users/urls.py
from django.urls import path , include
from .views import user_page , cabinet ,\
    write_post , my_articles ,\
    delete_article , update_article , \
    add_to_session , bucket , delete_bucket ,\
    articles , article_detail , add_comment , stat , js_examples
from .auth_views import login_ , register_ , logout_
from . import js_examples as js

app_name = 'client_app'

urlpatterns = [
    path('' , user_page , name='index'),
    path('cabinet/' , cabinet , name='cabinet'),
    path('write_post/' , write_post , name='write_post'),
    path('my-articles/' , my_articles , name='my_articles'),
    path('delete-article/<int:pk>/' , delete_article , name='delete_article'),
    path('update_article/<int:pk>/' , update_article , name='update_article'),
    path('add_to_session/<int:pk>/' , add_to_session , name='add_to_session'),
    path('delete_bucket/<int:pk>/' , delete_bucket , name='delete_bucket'),
    path('bucket/' , bucket , name='busket'),
    path('articles/' , articles , name='articles'),
    path('article-detail/<int:pk>/' , article_detail , name='article-detail'),
    path('add_comment/<int:id_article>/' , add_comment , name='add_comment'),
    path('stat/' , stat , name='stat'),
    path('js-examples/' , js_examples , name='js-examples'),
    path('ajax-examples/' , js.test , name='ajax-examples'),
]

auth_urls= [
    path('login_user/', login_, name='login'),
    path('register/', register_, name='register'),
    path('logout/', logout_, name='logout'),
]

urlpatterns += auth_urls

templates/partials/part_book_item.html
<div class="book-item">
    <h3> № {{ forloop.counter }}</h3>
    <h2> id {{ obj.id }}</h2>
    <p>
        <a href="/book-detail/{{obj.id}}/">{{ obj.title }}</a>
    </p>
    {% if obj.is_sale %}
    <p  >Старая цена -
        <span style="text-decoration: line-through; font-size: 12px;" >{{ obj.price }}</span>$</p>
    <p style="font-size: 18px;" >Новая цена - {{ obj.new_price }} $</p>
    {% else %}
    <p style="font-size: 18px;" >Цена - {{ obj.price }} $</p>
    {% endif %}

    <p>author - {{ obj.author.front_name }}</p>
    {% if page == 'home' %}
    <p>
        <a href="{% url 'client_app:add_to_session' pk=obj.id %}" class="btn btn-info">Добавить в корзину</a>
    </p>
    {% elif page == 'bucket' %}
        <a href="#" class="btn btn-primary">Купить</a>
        <a href="{% url 'client_app:delete_bucket' pk=obj.id %}" class="btn btn-primary">Удалить из корзины</a>
    {% endif %}
</div>