eshop/urls.py
from django.contrib import admin
from django.urls import path , include
from django.http import HttpResponse
from django.contrib.sessions.models import Session


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('home.urls')),
    path('user/' , include('users.urls' , namespace='client_app'))
]

home/urls.py
from django.urls import path
from .views import (home as H ,
    calculator , result ,
    exchange , about , book_detail , author_detail )

urlpatterns = [
    path('' , H),
    path('about/' , about),
    path('calculator/' , calculator),
    path('result/' , result),
    path('exchange/' , exchange),
    path('book-detail/<int:book_id>/' , book_detail),
    path('author-detail/<int:author_id>/' , author_detail),
]

users/urls.py
from django.urls import path , include
from .views import user_page , cabinet ,\
    write_post , my_articles ,\
    delete_article , update_article , \
    add_to_session , bucket , delete_bucket ,\
    articles , article_detail , add_comment , stat , js_examples
from .auth_views import login_ , register_ , logout_
from . import js_examples as js

app_name = 'client_app'

urlpatterns = [
    path('' , user_page , name='index'),
    path('cabinet/' , cabinet , name='cabinet'),
    path('write_post/' , write_post , name='write_post'),
    path('my-articles/' , my_articles , name='my_articles'),
    path('delete-article/<int:pk>/' , delete_article , name='delete_article'),
    path('update_article/<int:pk>/' , update_article , name='update_article'),
    path('add_to_session/<int:pk>/' , add_to_session , name='add_to_session'),
    path('delete_bucket/<int:pk>/' , delete_bucket , name='delete_bucket'),
    path('bucket/' , bucket , name='busket'),
    path('articles/' , articles , name='articles'),
    path('article-detail/<int:pk>/' , article_detail , name='article-detail'),
    path('add_comment/<int:id_article>/' , add_comment , name='add_comment'),
    path('stat/' , stat , name='stat'),
    path('js-examples/' , js_examples , name='js-examples'),
    path('ajax-examples/' , js.test , name='ajax-examples'),
]

auth_urls= [
    path('login_user/', login_, name='login'),
    path('register/', register_, name='register'),
    path('logout/', logout_, name='logout'),
]

urlpatterns += auth_urls

users/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class UserAuthor(models.Model):
	TYPE_USER_VIEW = (('fio', 'ФИО'), ('pseudo_name', 'Псевдимом'),)
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	bio = models.TextField(max_length=5000)
	type_view = models.CharField(choices=TYPE_USER_VIEW, max_length=len('pseudo_name'), verbose_name='Тип представления', blank=True, null=True)
	pseudoname = models.CharField(max_length=150, verbose_name='Псевдоним', blank=True, null=True)

	def get_type_view(self):
		if self.type_view == 'fio':
			return f'{self.user.first_name} {self.user.last_name}'
		elif self.type_view == 'pseudo_name':
			return self.pseudoname
		else:
			return self.user.username


	def __str__(self):
		return self.user.username


class Article(models.Model):
	author  = models.ForeignKey(UserAuthor , on_delete=models.SET_NULL , null=True)
	title  = models.CharField(max_length=255 , verbose_name='Заголовок статьи')
	lead  = models.CharField(max_length=500 , verbose_name='Краткое описание статьи')
	content  = models.TextField(max_length=15000 , verbose_name='Контент статьи')
	count_view = models.IntegerField(default=0)

	def __str__(self):
		return f'{self.title} {self.author.user.username}'

	def get_comments(self):
		return Comment.objects.filter(article=self)


class Comment(models.Model):
	user  = models.ForeignKey(UserAuthor , on_delete=models.CASCADE)
	article  = models.ForeignKey(Article , on_delete=models.CASCADE)
	text  = models.TextField(max_length=500 , blank=True, null=True)
	date = models.DateTimeField(auto_now_add=True)
	__str__ = lambda self: self.text

users/forms.py
from django import forms
from home.models import Book
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserAuthor , Article , Comment

class BookForm(forms.ModelForm):
	class Meta:
		model = Book
		# fields  = ['title']
		exclude=['author']


class SignUpForm(UserCreationForm):
	first_name  = forms.CharField(max_length=100 , required=False , label='Имя')
	last_name  = forms.CharField(max_length=100 , required=False , label='Фамилия')
	email  = forms.EmailField(max_length=254)


	def save(self , *args , **kwargs):
		data = self.cleaned_data
		django_user  = User.objects.create_user(
			username=data['username'],
			first_name=data['first_name'],
			last_name=data['last_name'],
			password=data['password1'],
			email=data['email'],
			is_active = True
		)
		UserAuthor.objects.create(user=django_user)
		return django_user


class UserAuthorForm(forms.ModelForm):
	class Meta:
		model = UserAuthor
		exclude  = ['user']


class ArticleForm(forms.ModelForm):
	class Meta:
		model  = Article
		exclude = ['author' , 'count_view']


	def save(self , *args , **kwargs):
		if kwargs.get('author'):
			current_user  = kwargs.pop('author')
			self.instance.author = current_user
		self.instance.save()

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		exclude  = ['user' , 'article']

users/views.py
from django.shortcuts import render, redirect
from .forms import BookForm, UserAuthorForm, ArticleForm , CommentForm
from .models import UserAuthor, Article , Comment
from home.models import Book
from django.http import JsonResponse
# Create your views here.
from django.http import HttpResponse


def user_page(request):
	ctx = {}
	ctx['form'] = BookForm()
	if request.method == 'GET':
		return render(request, 'users/index.html', ctx)
	elif request.method == 'POST':
		form = BookForm(request.POST)
		if form.is_valid():
			form.save()
			ctx['success'] = True
		return render(request, 'users/index.html', ctx)


def cabinet(request):
	ctx = {}
	ctx['cabinet_tab'] = 'profile'
	if request.method == 'GET':
		try:
			user_author = UserAuthor.objects.get(user=request.user.id)
			ctx['form'] = UserAuthorForm(instance=user_author)
		except Exception as e:
			ctx['form'] = UserAuthorForm
	if request.method == 'POST':
		form = UserAuthorForm(request.POST)
		if form.is_valid():
			user_author = UserAuthor.objects.get(user=request.user.id)
			user_author.bio = form.cleaned_data['bio']
			user_author.type_view = form.cleaned_data['type_view']
			user_author.pseudoname = form.cleaned_data['pseudoname']
			user_author.save()
			ctx['form'] = UserAuthorForm(instance=user_author)
			ctx['saved'] = True
	return render(request, 'users/cabinet/profile.html', ctx)


def write_post(request):
	ctx = {}
	ctx['cabinet_tab'] = 'write_post'
	ctx['form'] = ArticleForm
	user = UserAuthor.objects.get(user=request.user.id)
	if request.method == 'POST':
		form = ArticleForm(request.POST)
		if form.is_valid():
			form.save(author=user)
			ctx['saved'] = True
	return render(request, 'users/cabinet/write_post.html', ctx)


def my_articles(request):
	ctx = {}
	all_articles = Article.objects.filter(author__user_id=request.user.id)
	ctx['articles'] = all_articles
	ctx['cabinet_tab'] = 'my_articles'
	return render(request, 'users/cabinet/my_articles.html', ctx)


def delete_article(request, pk):
	print('delete request' , pk)
	try:
		article = Article.objects.get(id=pk)
		article.delete()
		return JsonResponse({
			'delete': True
		})
	except Exception as e:
		return JsonResponse({
			'error': True,
			'msg': str(e)
		})

	# return redirect('client_app:my_articles')


def update_article(request, pk):
	ctx = {}
	article = Article.objects.get(pk=pk, author__user_id=request.user.id)
	form = ArticleForm(instance=article)
	ctx['form'] = form
	if request.method == 'POST':
		form = ArticleForm(request.POST , instance=article)
		if form.is_valid():
			form.save()
			return redirect('client_app:my_articles')
		else:
			ctx['form'] = form
	return render(request, 'users/cabinet/write_post.html', ctx)


def add_to_session(request , pk):
	articles_in_session  = request.session.get('books_bucket' , [])
	print('before append!')
	print(request.session.get('books_bucket' , []))
	if pk not in articles_in_session:
		articles_in_session.append(pk)
	request.session['books_bucket'] = articles_in_session
	print('after append!')
	print(request.session.get('books_bucket' , []))
	return redirect('/')

def bucket(request):
	ctx  = {}
	books_ids = request.session.get('books_bucket' , [])
	if books_ids:
		all_books = [Book.objects.get(pk=book_id) for book_id in books_ids]
		total_price = 0
		for book in all_books:
			if book.is_sale and book.new_price:
				total_price += book.new_price
			else:
				total_price += book.price
		ctx['books'] = all_books
		ctx['total_price'] = total_price
	return render(request , 'users/bucket.html' , ctx)


def delete_bucket(request , pk):
	books_ids = request.session.get('books_bucket' , [])
	if pk in books_ids:
		books_ids.remove(pk)
		request.session['books_bucket'] = books_ids
		return redirect('client_app:busket')



def articles(request):
	ctx  = {}
	all_articles = Article.objects.all().order_by('-id')
	ctx['articles'] = all_articles
	return render(request , 'users/all_articles.html' , ctx)



def article_detail(request , pk):
	ctx  = {}
	ctx['article'] = Article.objects.get(pk=pk)
	ctx['form'] = CommentForm
	return render(request , 'users/article.html' , ctx)


def add_comment(request , id_article):
	article = Article.objects.get(pk=id_article)
	comment_author  = UserAuthor.objects.get(user_id=request.user.id)
	form = CommentForm(request.POST)
	if form.is_valid():
		text = form.cleaned_data['text']
		props = {
			'user': comment_author,
			'article': article,
			'text': text,
		}
		Comment.objects.create(**props)
		print('article ' , article)
		print('comment_author ' , comment_author)
		print('text ' , text)
	# print('add_comment ' , id_article)
	return redirect('client_app:article-detail' ,pk=id_article)

def stat(request):
	ctx  = {
		'labels': ['one' , 'two' , 'three'],
		'data': [7.5,3 , 10],
	}

	return render(request , 'users/cabinet/stat.html' , ctx)

def js_examples(request):
	ctx  = {}
	return render(request , 'users/examples_js.html' , ctx)

templates/users/cabinet/my_articles.html
{% extends 'users/cabinet/profile.html'  %}


{% block inside_cabinet %}

<h1>My articles!</h1>

<span id="loader" style="color: blue; font-size: 24px; display: none;">Deleting ...</span>
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Заголовок</th>
        <th scope="col">Кол-во просмотров</th>
        <th scope="col">Кол-во комментов</th>
        <th scope="col">Действие</th>
    </tr>
    </thead>
    <tbody>
    {% for article in articles %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{article.title}}</td>
        <td>{{article.count_view}}</td>
        <td>
            <a href="">
                Просмотреть {{article.get_comments | length }}
            </a>
        </td>
        <td>
            <a class="c b a x delete-v1 js-delete"
               href="{% url 'client_app:delete_article' pk=article.id %}">Удалить</a>
            <a href="{% url 'client_app:update_article' pk=article.id %}">Изменить</a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

{% block extra_js %}
<script src="https://code.jquery.com/jquery-3.5.0.min.js"
        integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>
<script>
    // alert('asdsad');
    $('.js-delete').click(function (e) {
        e.preventDefault();
        if (confirm('delete ?')) {
            var url = $(this).attr('href');
            var self = $(this);
            $('#loader').show();
            setTimeout(function () {
                $.ajax({
                    method: 'GET',
                    url: url
                }).done(function (response) {
                    if (response.delete) {
                        console.log("$(this).closest('tr') ", $(this));
                        self.closest('tr').hide();
                        $('#loader').hide();
                    }
                    console.log(response);
                })
            }, 1500)
        }


        // console.log('click by delete btn!');
    })
</script>
{% endblock extra_js %}

templates/users/cabinet/profile.html
{% extends 'index.html' %}

{% block content %}
<h1>Личный кабинет {{ request.user.username }} !</h1>

<style>
    .column {
        display: flex;
        flex-direction: column;
    }
</style>

    <div>
        <input type="number" name="first">
        <input type="number" name="second">
        <button id="btn">Calc!</button>
        <span id="result"></span>
    </div>

    <script>
        var btn  = document.getElementById('btn');
        btn.addEventListener('click' , function(){
            var first  = parseFloat(document.querySelector('input[name="first"]').value);
            var second  = parseFloat(document.querySelector('input[name="second"]').value);
            let result_val = first  +second;
            document.getElementById('result').innerHTML = result_val;
        })
    </script>
<div class="row">
    <div class="col-md-3 column">
        <a class="btn {% if cabinet_tab == 'profile' %}btn-primary {% endif %}" href="{% url 'client_app:cabinet' %}">Настройки профиля</a>
        <a class="btn {% if cabinet_tab == 'write_post' %}btn-primary {% endif %}" href="{% url 'client_app:write_post' %}">Написать статью</a>
        <a class="btn {% if cabinet_tab == 'my_articles' %}btn-primary {% endif %} " href="{% url 'client_app:my_articles' %}">Все статьи</a>
        <a class="btn " href="">Мои рефераллы</a>
        <a class="btn " href="{% url 'client_app:stat' %}">Статистика</a>
        <a class="btn " href="{% url 'client_app:js-examples' %}">js-examples</a>
    </div>


    <div class="col-md-9">
        {% block inside_cabinet %}
            {% if saved %}
                 <p class="alert alert-success">Данные успешно сохранены!</p>
            {% endif %}
            <form action="." method="post">
                {% csrf_token %}
                {% for f in form %}
                <div>
                    <label for="">{{f.label}}</label>
                    {{f}}
                </div>
                {% endfor %}
                <button class="btn btn-success"> Save</button>
            </form>
        {% endblock %}
    </div>
</div>
{% endblock  %}

templates/users/cabinet/stat.html
{% extends 'users/cabinet/profile.html' %}

{% block inside_cabinet %}
<h1>Stat</h1>
 <div id="container" style="width: 75%;">
    <canvas id="test"></canvas>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script>


    var config = {
      // type: 'pie',
      type: 'line',
      // type: 'bar',
      data: {
        datasets: [{
          data: {{ data|safe }},
        color: [
            'red'
        ],
          backgroundColor: [
            '#696969', '#808080', '#A9A9A9', '#C0C0C0', '#D3D3D3'
          ],
          label: 'stat test'
        }],
        labels: {{ labels|safe }}
      },
      options: {
        //     scales: {
        //     yAxes: [{
        //         ticks: {
        //             beginAtZero: true
        //         }
        //     }]
        // },
        responsive: true
      }
    };

    window.onload = function() {
      var ctx = document.getElementById('test').getContext('2d');
      window.myPie = new Chart(ctx, config);
    };

  </script>


{% endblock %}

templates/users/cabinet/write_post.html
{% extends 'users/cabinet/profile.html' %}

{% block inside_cabinet %}
<h1>Write post!!!</h1>

{% if saved %}
<p class="alert alert-success"> Статью успешно сохранили! </p>
{% endif %}
<form action="." method="post">
    {% csrf_token %}
    {% for f in form %}
        <div>
            <label for="">{{ f.label }}</label>
            {{f}}
        </div>
    {% endfor %}
    <button class="btn btn-info"> Save  </button>
</form>

{% endblock %}