eshop/urls.py
from django.contrib import admin
from django.urls import path , include
from django.http import HttpResponse
from django.contrib.sessions.models import Session


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('home.urls')),
    path('user/' , include('users.urls' , namespace='client_app'))
]

home/urls.py
from django.urls import path
from .views import (home as H ,
    calculator , result ,
    exchange , about , book_detail , author_detail )

urlpatterns = [
    path('' , H),
    path('about/' , about),
    path('calculator/' , calculator),
    path('result/' , result),
    path('exchange/' , exchange),
    path('book-detail/<int:book_id>/' , book_detail),
    path('author-detail/<int:author_id>/' , author_detail),
]

users/urls.py
from django.urls import path , include
from .views import user_page , cabinet ,\
    write_post , my_articles ,\
    delete_article , update_article , \
    add_to_session , bucket , delete_bucket ,\
    articles , article_detail , add_comment , stat , js_examples
from .auth_views import login_ , register_ , logout_
from . import js_examples as js

app_name = 'client_app'

urlpatterns = [
    path('' , user_page , name='index'),
    path('cabinet/' , cabinet , name='cabinet'),
    path('write_post/' , write_post , name='write_post'),
    path('my-articles/' , my_articles , name='my_articles'),
    path('delete-article/<int:pk>/' , delete_article , name='delete_article'),
    path('update_article/<int:pk>/' , update_article , name='update_article'),
    path('add_to_session/<int:pk>/' , add_to_session , name='add_to_session'),
    path('delete_bucket/<int:pk>/' , delete_bucket , name='delete_bucket'),
    path('bucket/' , bucket , name='busket'),
    path('articles/' , articles , name='articles'),
    path('article-detail/<int:pk>/' , article_detail , name='article-detail'),
    path('add_comment/<int:id_article>/' , add_comment , name='add_comment'),
    path('stat/' , stat , name='stat'),
    path('js-examples/' , js_examples , name='js-examples'),
    path('ajax-examples/' , js.test , name='ajax-examples'),
]

auth_urls= [
    path('login_user/', login_, name='login'),
    path('register/', register_, name='register'),
    path('logout/', logout_, name='logout'),
]

urlpatterns += auth_urls

templates/includes/footer.html
<footer style="height: 200px; background: cornflowerblue;">


    This is footer
</footer>

templates/includes/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Home page</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item {% if tab == 'home' %} active {% endif %}">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link  {% if tab == 'about' %} active {% endif %}" href="/about/">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
            <li class="nav-item">
                <a class="nav-link  {% if tab == 'about' %} active {% endif %}" href="{% url 'client_app:index' %}">Examples 1</a>
            </li>
             <li class="nav-item">
                <a class="nav-link  " href="{% url 'client_app:articles' %}">Статьи</a>
            </li>
        </ul>
    </div>
    <a href="{% url 'client_app:busket' %}" class="btn btn-info">Корзина {{request.session.books_bucket | length }}</a> |
    {% if not request.user.is_authenticated %}
    <a class="btn btn-primary" href="{% url 'client_app:login' %}">Вход</a> |
    <a class="btn btn-primary" href="{% url 'client_app:register' %}">Регистрация</a>
    {% else %}
    <a class="btn btn-danger" href="{% url 'client_app:logout' %}">Log out({{ request.user.username }})</a>
    |
    <a class="btn btn-danger" href="{% url 'client_app:cabinet' %}">Кабинет</a>
    {% endif %}
</nav>