eshop/urls.py
from django.contrib import admin
from django.urls import path , include
from django.http import HttpResponse
from django.contrib.sessions.models import Session


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('home.urls')),
    path('user/' , include('users.urls' , namespace='client_app'))
]

home/urls.py
from django.urls import path
from .views import (home as H ,
    calculator , result ,
    exchange , about , book_detail , author_detail )

urlpatterns = [
    path('' , H),
    path('about/' , about),
    path('calculator/' , calculator),
    path('result/' , result),
    path('exchange/' , exchange),
    path('book-detail/<int:book_id>/' , book_detail),
    path('author-detail/<int:author_id>/' , author_detail),
]

users/urls.py
from django.urls import path , include
from .views import user_page , cabinet ,\
    write_post , my_articles ,\
    delete_article , update_article , \
    add_to_session , bucket , delete_bucket ,\
    articles , article_detail , add_comment , stat , js_examples
from .auth_views import login_ , register_ , logout_
from . import js_examples as js

app_name = 'client_app'

urlpatterns = [
    path('' , user_page , name='index'),
    path('cabinet/' , cabinet , name='cabinet'),
    path('write_post/' , write_post , name='write_post'),
    path('my-articles/' , my_articles , name='my_articles'),
    path('delete-article/<int:pk>/' , delete_article , name='delete_article'),
    path('update_article/<int:pk>/' , update_article , name='update_article'),
    path('add_to_session/<int:pk>/' , add_to_session , name='add_to_session'),
    path('delete_bucket/<int:pk>/' , delete_bucket , name='delete_bucket'),
    path('bucket/' , bucket , name='busket'),
    path('articles/' , articles , name='articles'),
    path('article-detail/<int:pk>/' , article_detail , name='article-detail'),
    path('add_comment/<int:id_article>/' , add_comment , name='add_comment'),
    path('stat/' , stat , name='stat'),
    path('js-examples/' , js_examples , name='js-examples'),
    path('ajax-examples/' , js.test , name='ajax-examples'),
]

auth_urls= [
    path('login_user/', login_, name='login'),
    path('register/', register_, name='register'),
    path('logout/', logout_, name='logout'),
]

urlpatterns += auth_urls

users/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class UserAuthor(models.Model):
	TYPE_USER_VIEW = (('fio', 'ФИО'), ('pseudo_name', 'Псевдимом'),)
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	bio = models.TextField(max_length=5000)
	type_view = models.CharField(choices=TYPE_USER_VIEW, max_length=len('pseudo_name'), verbose_name='Тип представления', blank=True, null=True)
	pseudoname = models.CharField(max_length=150, verbose_name='Псевдоним', blank=True, null=True)

	def get_type_view(self):
		if self.type_view == 'fio':
			return f'{self.user.first_name} {self.user.last_name}'
		elif self.type_view == 'pseudo_name':
			return self.pseudoname
		else:
			return self.user.username


	def __str__(self):
		return self.user.username


class Article(models.Model):
	author  = models.ForeignKey(UserAuthor , on_delete=models.SET_NULL , null=True)
	title  = models.CharField(max_length=255 , verbose_name='Заголовок статьи')
	lead  = models.CharField(max_length=500 , verbose_name='Краткое описание статьи')
	content  = models.TextField(max_length=15000 , verbose_name='Контент статьи')
	count_view = models.IntegerField(default=0)

	def __str__(self):
		return f'{self.title} {self.author.user.username}'

	def get_comments(self):
		return Comment.objects.filter(article=self)


class Comment(models.Model):
	user  = models.ForeignKey(UserAuthor , on_delete=models.CASCADE)
	article  = models.ForeignKey(Article , on_delete=models.CASCADE)
	text  = models.TextField(max_length=500 , blank=True, null=True)
	date = models.DateTimeField(auto_now_add=True)
	__str__ = lambda self: self.text

users/forms.py
from django import forms
from home.models import Book
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserAuthor , Article , Comment

class BookForm(forms.ModelForm):
	class Meta:
		model = Book
		# fields  = ['title']
		exclude=['author']


class SignUpForm(UserCreationForm):
	first_name  = forms.CharField(max_length=100 , required=False , label='Имя')
	last_name  = forms.CharField(max_length=100 , required=False , label='Фамилия')
	email  = forms.EmailField(max_length=254)


	def save(self , *args , **kwargs):
		data = self.cleaned_data
		django_user  = User.objects.create_user(
			username=data['username'],
			first_name=data['first_name'],
			last_name=data['last_name'],
			password=data['password1'],
			email=data['email'],
			is_active = True
		)
		UserAuthor.objects.create(user=django_user)
		return django_user


class UserAuthorForm(forms.ModelForm):
	class Meta:
		model = UserAuthor
		exclude  = ['user']


class ArticleForm(forms.ModelForm):
	class Meta:
		model  = Article
		exclude = ['author' , 'count_view']


	def save(self , *args , **kwargs):
		if kwargs.get('author'):
			current_user  = kwargs.pop('author')
			self.instance.author = current_user
		self.instance.save()

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		exclude  = ['user' , 'article']

users/views.py
from django.shortcuts import render, redirect
from .forms import BookForm, UserAuthorForm, ArticleForm , CommentForm
from .models import UserAuthor, Article , Comment
from home.models import Book
from django.http import JsonResponse
# Create your views here.
from django.http import HttpResponse


def user_page(request):
	ctx = {}
	ctx['form'] = BookForm()
	if request.method == 'GET':
		return render(request, 'users/index.html', ctx)
	elif request.method == 'POST':
		form = BookForm(request.POST)
		if form.is_valid():
			form.save()
			ctx['success'] = True
		return render(request, 'users/index.html', ctx)


def cabinet(request):
	ctx = {}
	ctx['cabinet_tab'] = 'profile'
	if request.method == 'GET':
		try:
			user_author = UserAuthor.objects.get(user=request.user.id)
			ctx['form'] = UserAuthorForm(instance=user_author)
		except Exception as e:
			ctx['form'] = UserAuthorForm
	if request.method == 'POST':
		form = UserAuthorForm(request.POST)
		if form.is_valid():
			user_author = UserAuthor.objects.get(user=request.user.id)
			user_author.bio = form.cleaned_data['bio']
			user_author.type_view = form.cleaned_data['type_view']
			user_author.pseudoname = form.cleaned_data['pseudoname']
			user_author.save()
			ctx['form'] = UserAuthorForm(instance=user_author)
			ctx['saved'] = True
	return render(request, 'users/cabinet/profile.html', ctx)


def write_post(request):
	ctx = {}
	ctx['cabinet_tab'] = 'write_post'
	ctx['form'] = ArticleForm
	user = UserAuthor.objects.get(user=request.user.id)
	if request.method == 'POST':
		form = ArticleForm(request.POST)
		if form.is_valid():
			form.save(author=user)
			ctx['saved'] = True
	return render(request, 'users/cabinet/write_post.html', ctx)


def my_articles(request):
	ctx = {}
	all_articles = Article.objects.filter(author__user_id=request.user.id)
	ctx['articles'] = all_articles
	ctx['cabinet_tab'] = 'my_articles'
	return render(request, 'users/cabinet/my_articles.html', ctx)


def delete_article(request, pk):
	print('delete request' , pk)
	try:
		article = Article.objects.get(id=pk)
		article.delete()
		return JsonResponse({
			'delete': True
		})
	except Exception as e:
		return JsonResponse({
			'error': True,
			'msg': str(e)
		})

	# return redirect('client_app:my_articles')


def update_article(request, pk):
	ctx = {}
	article = Article.objects.get(pk=pk, author__user_id=request.user.id)
	form = ArticleForm(instance=article)
	ctx['form'] = form
	if request.method == 'POST':
		form = ArticleForm(request.POST , instance=article)
		if form.is_valid():
			form.save()
			return redirect('client_app:my_articles')
		else:
			ctx['form'] = form
	return render(request, 'users/cabinet/write_post.html', ctx)


def add_to_session(request , pk):
	articles_in_session  = request.session.get('books_bucket' , [])
	print('before append!')
	print(request.session.get('books_bucket' , []))
	if pk not in articles_in_session:
		articles_in_session.append(pk)
	request.session['books_bucket'] = articles_in_session
	print('after append!')
	print(request.session.get('books_bucket' , []))
	return redirect('/')

def bucket(request):
	ctx  = {}
	books_ids = request.session.get('books_bucket' , [])
	if books_ids:
		all_books = [Book.objects.get(pk=book_id) for book_id in books_ids]
		total_price = 0
		for book in all_books:
			if book.is_sale and book.new_price:
				total_price += book.new_price
			else:
				total_price += book.price
		ctx['books'] = all_books
		ctx['total_price'] = total_price
	return render(request , 'users/bucket.html' , ctx)


def delete_bucket(request , pk):
	books_ids = request.session.get('books_bucket' , [])
	if pk in books_ids:
		books_ids.remove(pk)
		request.session['books_bucket'] = books_ids
		return redirect('client_app:busket')



def articles(request):
	ctx  = {}
	all_articles = Article.objects.all().order_by('-id')
	ctx['articles'] = all_articles
	return render(request , 'users/all_articles.html' , ctx)



def article_detail(request , pk):
	ctx  = {}
	ctx['article'] = Article.objects.get(pk=pk)
	ctx['form'] = CommentForm
	return render(request , 'users/article.html' , ctx)


def add_comment(request , id_article):
	article = Article.objects.get(pk=id_article)
	comment_author  = UserAuthor.objects.get(user_id=request.user.id)
	form = CommentForm(request.POST)
	if form.is_valid():
		text = form.cleaned_data['text']
		props = {
			'user': comment_author,
			'article': article,
			'text': text,
		}
		Comment.objects.create(**props)
		print('article ' , article)
		print('comment_author ' , comment_author)
		print('text ' , text)
	# print('add_comment ' , id_article)
	return redirect('client_app:article-detail' ,pk=id_article)

def stat(request):
	ctx  = {
		'labels': ['one' , 'two' , 'three'],
		'data': [7.5,3 , 10],
	}

	return render(request , 'users/cabinet/stat.html' , ctx)

def js_examples(request):
	ctx  = {}
	return render(request , 'users/examples_js.html' , ctx)

templates/users/all_articles.html
{% extends 'index.html' %}


{% block content %}
<h1>All articles!</h1>
<div class="row">
    {% for article in articles %}
    <div class="col-md-3">
        <p>{{article.title}}</p>
        <p><a href="">Автор статьи {{article.author.get_type_view}}</a></p>
        <a  class="btn btn-danger" href="{% url 'client_app:article-detail' pk=article.id  %}"> Прочитать </a>
    </div>
    {% endfor %}
</div>
{% endblock content %}

templates/users/article.html
{% extends 'index.html' %}


{% block content %}
<h1>{{ article.title }}</h1>
<p>Автор статьи  {{ article.author.get_type_view }}</p>
<h3>Текст статьи</h3>
<div>
        {{ article.content }}
</div>
<h2>Комментарии ({{ article.get_comments|length }}) : </h2>

{% if article.get_comments %}

{% for comment in article.get_comments %}
    <div>
        <a href="">#{{comment.user.get_type_view}}</a>
        <p>
        {{ comment.text }}
        </p>
    </div>
{% endfor %}
{% else %}
    <p class="alert alert-info"> В данной статье пока нет комментов! </p>
{% endif %}

<hr>
<p>Оставьте свой комментарий.</p>

{% if request.user.is_authenticated %}
<form action="{% url 'client_app:add_comment' id_article=article.id %}" method="post">
    {% csrf_token %}
{{ form }}
    <br>
    <button class="btn btn-success"> Прикрепить коммент </button>
    </form>
{% else %}
<p class="alert alert-danger">
    Комментарии могут оставлять только авторизованые пользователи

    <a href="{% url 'client_app:login' %}">Войти</a>
</p>
{% endif %}
{% endblock content %}

templates/users/bucket.html
{% extends 'index.html' %}

{% block content %}
<h1>Корзина {{total_price}} $ </h1>

<div class="wrap">
    {% for i in books %}
          {% include 'partials/part_book_item.html' with obj=i page='bucket' %}
    {% endfor %}
</div>

{% endblock %}

templates/users/examples_js.html
{% extends 'index.html' %}


{% block content %}
<h1>Js examples!</h1>
<!--<div>-->
<!--    <button id="btn">click me!!!</button>-->
<!--</div>-->
<!--<div id="id_">-->
<!--    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur commodi consectetur consequuntur dicta ducimus,-->
<!--    eaque est hic laboriosam magnam pariatur provident quaerat quas quod similique tempore, veniam vero? Fugiat,-->
<!--    voluptates.-->
<!--</div>-->

<!--<span id="timeout">0</span>-->

<!--<span id="output"></span>-->
<!--<form id="form" action="">-->
<!--    <input type="text" name="first">-->
<!--    <input type="text" name="second">-->
<!--    <input type="text" name="second">-->
<!--    <input type="text" name="second">-->
<!--    <input type="text" name="second">-->
<!--    <input type="text" name="second">-->
<!--    <input type="text" name="second">-->
<!--    <button>Calc!</button>-->
<!--</form>-->
<h2>AJAX EXAMPLES!!!</h2>
<p class="alert alert-info" style="display: none;">Loading .... </p>
<div>
    <button id="send_request">Send request to python!</button>
</div>
<div id="output_authors">

</div>


{% endblock content %}


{% block extra_js %}
<script>

    /* block comment
    *
    *
    *
    *
    * comment!
    *
    *  */
    var a = 234;
    var b = 0.5;
    var b1 = true;
    var b2 = false;
    var u = undefined;
    var u1 = null;
    var s = 'sajd kasjdasd';
    var arr = [1, 23, true, 'asdsad'];
    var dict = {
        'a': 34,
        'b': {
            'c': 56
        }
    }

    // console.log(a, b, b1, u, u1, arr, dict, dict['b']);

    // alert('Hello js!');
    /*
    var res  = confirm('y or n?');
    if (res == true){
        alert('its TRUE!!!!');
    } else{
        alert('its FALSE!!!');
    }*/
    // var str = prompt('string >>>>', 'default value');
    // console.log(str, 'str');

    /*
    function functionName(a, b) {
        for(var i=0; i < 10; i++){
            console.log('i =' , i);
        }
        console.log('ii ==' , i);
        console.log(arguments);
        console.log('function called!' , a , b);
    }

    functionName(1,2,3,4,5,true,'asdasdasd')
    */

    var btn = document.getElementById('btn');
    var block_text = document.getElementById('id_');
    var form = document.getElementById('form');
    var output = document.getElementById('output');

    btn.addEventListener('click', function () {
        console.log(block_text.innerHTML)
        if (block_text.style.display == 'none') {
            block_text.style.display = 'block';
        } else {
            block_text.style.display = 'none';
        }
    })

    block_text.addEventListener('click', function () {
        console.log('clicked by text!!!!!');
    })


    setInterval(function () {
        var timeout = document.getElementById('timeout');
        var timeout_value = +timeout.innerHTML;
        timeout.innerHTML = timeout_value + 1;
    }, 500)

    form.addEventListener('submit', function (ev) {
        ev.preventDefault();
        var this_form = ev.target;
        var inputs = this_form.querySelectorAll('input');
        var sum = 0;
        for (var i = 0; i < inputs.length; i += 1) {
            if (inputs[i].value) {
                sum += parseInt(inputs[i].value);
            }
            console.log(inputs[i].value)
        }
        output.innerHTML = sum;
        console.log(sum);
    })

</script>


<script src="https://code.jquery.com/jquery-3.5.0.min.js"
        integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>

<script>
    var user_id = '{{ request.user.id }}';
    // ajax
    console.log('user_id ', user_id);
    var x = new XMLHttpRequest();
    console.log($);
    $('#send_request').click(function () {
        if (user_id === 'None') {
            alert('Need auth!')
            return;
        }
        $('.alert-info').show();
        setTimeout(function () {
            $.ajax({
                method: 'GET',
                url: '/user/ajax-examples/',
                data: {
                    'a': 123,
                    'b': true
                }
            }).done(function (x) {
                var global_template = '';
                for (var i = 0; i < x.authors.length; i++) {
                    var template_ = `<p> ${x.authors[i].name}  ${x.authors[i].surname}</p>`;
                    global_template += template_;
                }
                $('#output_authors').html(global_template);
                $('.alert-info').hide();
            })
        }, 2500)

    });
    console.log();
</script>
{% endblock extra_js %}

templates/users/index.html
{% extends 'index.html' %}

{% block content %}
<h1>Users page!!</h1>

<p>{{ 'lower'|upper }}</p>
<p>{{ 'asdsdASFASfSвфывфывЫВФЫЫВ'|lower }}</p>

{% if success %}
<p class="alert alert-success">
    Мы сохранили данные!
</p>
{% endif %}
<form action="." method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        {{ field.label }}
        {{ field }}
    </div>
    {% endfor %}
    <button class="btn btn-primary">Save Book!</button>
</form>
{%  endblock %}